# Generated by Django 4.1.3 on 2022-11-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_slug_productreview_slugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slugs',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='slugs',
            new_name='slug',
        ),
    ]
